name: Daily News

on:
  workflow_dispatch:
  schedule:
    - cron: "0 9 * * *"

jobs:
  send_news:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"
      - name: Install Python packages
        run: |
          python -m pip install --upgrade pip
          pip install python-dotenv eventregistry
      - name: Run script
        env:
          NEWSAPI_KEY: ${{ secrets.NEWSAPI_KEY }}
        run: python scripts/newsletter.py
      - name: Commit and push articles.JSON
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add articles.JSON
          git commit -m "Update articles.JSON from workflow" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
